# Generated by Django 5.1 on 2024-09-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userblooddonate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userbloodrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
