# Generated by Django 5.1 on 2024-09-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorprofile',
            old_name='phone_number',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='userblooddonate',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userbloodrequest',
            name='phone_number',
        ),
    ]
