# Generated by Django 5.1 on 2024-09-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_rename_phone_number_donorprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
