# Generated by Django 5.1 on 2024-09-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_userblooddonate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblooddonate',
            name='details',
        ),
    ]
