# Generated by Django 5.1 on 2024-08-31 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BloodCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_date', models.DateTimeField()),
                ('district', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=4)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_donors', to=settings.AUTH_USER_MODEL)),
                ('request_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_history', to='bloods.bloodrequest')),
                ('donation_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donates_history', to='bloods.donationrequest')),
            ],
        ),
    ]
